### ISSUE TITLE
Sending review to Outlook distribution lists doesn't work

### ISSUE THREAD

**Issue by meyerdenney** [Coldarn/twiceover-client#7]
When adding a distribution list to a code review, the members of the list do not receive the email. This is true when entering the distribution list in the following formats:

SomeScrumTeam@fake.com
Some Scrum Team SomeScrumTeam@fake.com

Oddly enough, other reviewers whose individual email address was added to the review will see the distribution list show up in the To line of the email when using the SomeScrumTeam@fake.com format.

**Comment by Coldarn** [comment]
I believe this has been fixed by 162f58e36ad2f7d3bb0392ace43c9ea127e09566.

**Comment by Coldarn** [comment]
To your second point about distribution list email delivery, twiceover-server doesn't treat them specially in any way from other email addresses, so I suspect that failed delivery to DL members is a spam or mail filtering issue in Exchange. We'll have to investigate our internal SMTP server and other infrastructure further to validate that.
